# PaperWhitelistPlugin Configuration

# Web Server Settings
web:
  port: 8080
  # IP address to bind to (0.0.0.0 for all interfaces)
  bind-address: "0.0.0.0"
  # Session timeout in minutes
  session-timeout: 30

# Database Settings
database:
  # H2 database file path (relative to plugin data folder)
  file: "whitelist.db"
  # Database username
  username: "admin"
  # Database password
  password: "password"

# Administrator Settings
admin:
  # BCrypt hashed password (generate using /whitelistweb hash <password>)
  password-hash: "$2a$10$EixZaY3s7vLpMsk6R6PwQO3Zl8jVQ5sW9dQ8eZ7X7X7X7X7X7X7X"
  # Default admin password (will be used if password-hash is not set, change immediately!)
  default-password: "admin123"

# Whitelist Settings
whitelist:
  # Prefix for bedrock edition players
  bedrock-prefix: "BE_"
  # Default user type when approved (TRIAL or MEMBER)
  default-user-type: "TRIAL"

# Logging Settings
logging:
  # Enable debug logging
  debug: false
  # Log file name (relative to plugin data folder)
  file: "plugin.log"