name: PaperWhitelistPlugin
version: 1.0.0
main: com.example.paperwhitelist.PaperWhitelistPlugin
api-version: 1.20
author: YourName
description: A web-based whitelist management plugin for Paper servers
website: https://github.com/yourusername/paper-whitelist-plugin
commands:
  whitelistweb:
    description: Manages the whitelist web interface
    usage: /<command> [reload|status]
    permission: paperwhitelist.admin
    permission-message: You don't have permission to use this command!